### ISSUE TITLE
Add Lock Statement Support for Completions

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-lang/ballerina#4771] opened 2018-02-21 09:47 UTC
Original issue - https://github.com/ballerina-lang/language-server/issues/112

**Description:**
Need to support https://github.com/ballerinalang/ballerina/pull/4508

**Related Issues:**
https://github.com/ballerinalang/ballerina/pull/4508

**Comment by nadeeshaan** [comment] 2018-02-21 11:02
Duplicate of https://github.com/ballerina-lang/ballerina/issues/4571 and Fixed with https://github.com/ballerina-lang/ballerina/pull/4694

**Closed by nadeeshaan** 2018-02-21 11:02 UTC
Labels: Severity/Critical, Type/Task, component/language-server
